### ISSUE TITLE
error in AppVersionConfig when used yowsup

### ISSUE THREAD

**Issue by joukerbr** [tgalal/consonance#2]
do you have this error??

error in AppVersionConfig when used  yowsup (whats version 2.21.5.14)

too many values to unpack (expected 3) include quarterly 

class AppVersionConfig(object):
    STR_TEMPLATE = """AppVersionConfig(
            primary={primary},
            secondary={secondary},
            tertiary={tertiary},
            **quarterly = {quarterly}**
        )"""

    def __init__(self, version):
        """
        :param version:
        :type version: str
        """
        dissected = version.split('.')
        assert len(dissected) > 3, "version must be in format x.y.z.w"
        self._primary, self._secondary, self._tertiary,**self._quarterly** = map(lambda v:int(v), dissected)

    def __str__(self):
        return self.STR_TEMPLATE.format(
            primary=self.primary,
            secondary=self.secondary,
            tertiary=self.tertiary,
            **quarterly=self.quarterly**
        )

    @property
    def primary(self):
        return self._primary

    @property
    def secondary(self):
        return self._secondary

    @property
    def tertiary(self):
        return self._tertiary
    
    **@property
    def quarterly(self):
        return self.quarterly**

**Comment by tgalal** [comment]
fixed
